### ISSUE TITLE
Apply for funding Python Software Foundation

### ISSUE THREAD

**Issue by sleepypioneer** [pythonpizza/hamburg.python.pizza#147]
Ask for 2000 pizza & drinks

**Comment by terezaif** [comment]
Form is rather extensive, we need to define better the CoC enforcement policy and address covid
- [ ] Code of Conduct Enforcement Policy
- [ ] covid policy and this is mandatory.. we deleted all the text 😅 maybe we can add a paragraph:
pls don't attend if you are experiencing flu-like symptoms

**Comment by terezaif** [comment]
I think also deploying the 2021 would be nice for reference..

and why do all past sites come as insecure on safari? @marcoacierno 💃

**Comment by terezaif** [comment]
Applied
