### ISSUE TITLE
fosstodon.org PythonPizza to be created

### ISSUE THREAD

**Issue by sleepypioneer** [pythonpizza/hamburg.python.pizza#157]

**Comment by sleepypioneer** [comment]
pythonpizza@fosstodon.org

**Comment by sleepypioneer** [comment]
still to do add icon (assets in github)

**Comment by cmaureir** [comment]
Profile is now updated. I couldn't use the repo header because it's in a `afdesign` format that I couldn't open, so I improvised. https://fosstodon.org/@pythonpizza

**Comment by cmaureir** [comment]
Password changed and moved the email to the one from hamburg,
