### ISSUE TITLE
Organise panel

### ISSUE THREAD

**Issue by sleepypioneer** [pythonpizza/hamburg.python.pizza#165]

**Comment by sleepypioneer** [comment]
- reach out to Noa if she would be interested to lead this

**Comment by sleepypioneer** [comment]
I forgot to ask Noa this 🙈 so I have emailed her today (8th september) but also said if she needs another week it is ok 🙂

**Comment by noatamir** [comment]
Want to assign this to me?

**Comment by sleepypioneer** [comment]
@noatamir if you're happy to track it here that would be awesome

**Comment by sleepypioneer** [comment]
@noatamir wanted to follow up here as Tereza and I synced today. We will soon announce the first round of speakers and would like to also put something (doesn't have to be the full thing) about the panel :)

**Comment by sleepypioneer** [comment]
due to unforeseen circumstances we will not run the panel for this addition ❤
